"use client";
import { useState, useEffect } from "react";
import { Download, Plus, FileText, CheckCircle2, X, Loader2, DollarSign } from "lucide-react";
import { useAuthStore } from "@/store/auth.store";
import { formatCurrency } from "@/lib/utils";
import { toast } from "sonner";
import { db } from "@/lib/firebase";
import {
  collection, onSnapshot, query, orderBy, where,
  addDoc, serverTimestamp, getDocs, doc, setDoc,
} from "firebase/firestore";

/* ─── Types ─── */
type Payslip = {
  id: string;
  month: string;
  basic: number;
  allowances: number;
  bonus: number;
  pf: number;
  tax: number;
  deductions: number;
  net: number;
  status: string;
  employeeId?: string;
  employeeName?: string;
  department?: string;
};

type EmpPayroll = {
  id: string;
  name: string;
  dept: string;
  salary: number;
  status: string;
  month: string;
  basic: number;
  allowances: number;
  bonus: number;
  pf: number;
  tax: number;
  deductions: number;
  net: number;
  employeeId: string;
};

/* ─── Payslip Print/Download Helper ─── */
function buildPayslipHtml(entry: { name: string; dept: string; month: string; basic: number; allowances: number; bonus: number; pf: number; tax: number; deductions: number; net: number; status?: string }) {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Payslip - ${entry.name} - ${entry.month}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 700px; margin: 40px auto; color: #333; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 13px; margin-bottom: 30px; }
    .row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
    .section-title { font-weight: bold; font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; color: #888; margin: 20px 0 8px; }
    .net { display: flex; justify-content: space-between; padding: 14px 16px; background: #e8f5e9; border-radius: 8px; margin-top: 24px; font-size: 16px; font-weight: bold; }
    .net-amount { font-size: 22px; color: #22C55E; }
  </style>
</head>
<body>
  <h1>Payslip — ${entry.month}</h1>
  <div class="subtitle">Employee: ${entry.name} &bull; ${entry.dept} &bull; ${entry.status ? `Status: ${entry.status}` : "Generated by HR"}</div>
  <div class="section-title">Earnings</div>
  <div class="row"><span>Basic Salary</span><span>₹${entry.basic.toLocaleString()}</span></div>
  <div class="row"><span>Allowances</span><span>₹${entry.allowances.toLocaleString()}</span></div>
  <div class="row"><span>Bonus</span><span>₹${entry.bonus.toLocaleString()}</span></div>
  <div class="row" style="font-weight:bold"><span>Gross Salary</span><span style="color:#22C55E">₹${(entry.basic + entry.allowances + entry.bonus).toLocaleString()}</span></div>
  <div class="section-title">Deductions</div>
  <div class="row"><span>Provident Fund</span><span style="color:#EF4444">- ₹${entry.pf.toLocaleString()}</span></div>
  <div class="row"><span>Income Tax</span><span style="color:#EF4444">- ₹${entry.tax.toLocaleString()}</span></div>
  <div class="row" style="font-weight:bold"><span>Total Deductions</span><span style="color:#EF4444">- ₹${entry.deductions.toLocaleString()}</span></div>
  <div class="net">
    <span>Net Salary</span>
    <span class="net-amount">₹${entry.net.toLocaleString()}</span>
  </div>
</body>
</html>`;
}

function openPrintWindow(html: string) {
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const w = window.open(url, "_blank");
  if (w) setTimeout(() => { w.print(); URL.revokeObjectURL(url); }, 500);
}

/* ─── Payslip View Modal ─── */
function PayslipModal({ entry, onClose }: { entry: EmpPayroll; onClose: () => void }) {
  return (
    <div style={{
      position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)",
      display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000,
    }} onClick={onClose}>
      <div className="card" style={{ padding: 32, width: 560, boxShadow: "var(--shadow-lg)", maxHeight: "90vh", overflowY: "auto" }}
        onClick={(e) => e.stopPropagation()}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}>
          <div>
            <div style={{ fontSize: 16, fontWeight: 700 }}>Payslip — {entry.month}</div>
            <div style={{ fontSize: 12, color: "var(--text-muted)", marginTop: 2 }}>{entry.name} · {entry.dept}</div>
          </div>
          <div style={{ display: "flex", gap: 8 }}>
            <button className="btn btn-secondary" style={{ gap: 6 }} onClick={() => {
              openPrintWindow(buildPayslipHtml(entry));
              toast.success(`Payslip for ${entry.name} opened for download!`);
            }}>
              <Download size={14} /> Download PDF
            </button>
            <button className="btn btn-ghost" style={{ padding: "6px 8px" }} onClick={onClose}>
              <X size={16} />
            </button>
          </div>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
          <div>
            <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-muted)", marginBottom: 12, letterSpacing: "0.05em", textTransform: "uppercase" }}>Earnings</div>
            {[
              { label: "Basic Salary",  value: formatCurrency(entry.basic) },
              { label: "Allowances",    value: formatCurrency(entry.allowances) },
              { label: "Bonus",         value: formatCurrency(entry.bonus) },
            ].map((item) => (
              <div key={item.label} style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid var(--border)" }}>
                <span style={{ fontSize: 13, color: "var(--text-secondary)" }}>{item.label}</span>
                <span style={{ fontSize: 13, fontWeight: 500 }}>{item.value}</span>
              </div>
            ))}
            <div style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", marginTop: 4 }}>
              <span style={{ fontSize: 13, fontWeight: 600 }}>Gross Salary</span>
              <span style={{ fontSize: 13, fontWeight: 700, color: "var(--accent-green)" }}>{formatCurrency(entry.basic + entry.allowances + entry.bonus)}</span>
            </div>
          </div>
          <div>
            <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-muted)", marginBottom: 12, letterSpacing: "0.05em", textTransform: "uppercase" }}>Deductions</div>
            {[
              { label: "Provident Fund", value: formatCurrency(entry.pf) },
              { label: "Income Tax",     value: formatCurrency(entry.tax) },
            ].map((item) => (
              <div key={item.label} style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid var(--border)" }}>
                <span style={{ fontSize: 13, color: "var(--text-secondary)" }}>{item.label}</span>
                <span style={{ fontSize: 13, fontWeight: 500, color: "var(--accent-red)" }}>- {item.value}</span>
              </div>
            ))}
            <div style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", marginTop: 4 }}>
              <span style={{ fontSize: 13, fontWeight: 600 }}>Total Deductions</span>
              <span style={{ fontSize: 13, fontWeight: 700, color: "var(--accent-red)" }}>- {formatCurrency(entry.deductions)}</span>
            </div>
          </div>
        </div>

        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 20, padding: "16px 20px", background: "var(--accent-green-dim)", borderRadius: "var(--radius-sm)", border: "1px solid rgba(34,197,94,0.2)" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <CheckCircle2 size={18} color="var(--accent-green)" />
            <span style={{ fontSize: 15, fontWeight: 700 }}>Net Salary</span>
          </div>
          <span style={{ fontSize: 22, fontWeight: 800, color: "var(--accent-green)" }}>{formatCurrency(entry.net)}</span>
        </div>
      </div>
    </div>
  );
}

/* ─── Main Page ─── */
export default function PayrollPage() {
  const { role, profile } = useAuthStore();
  const isAdmin = role === "super_admin" || role === "hr_admin";

  /* ── State ── */
  const [viewEntry, setViewEntry] = useState<EmpPayroll | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  /* Admin: employee payroll from Firestore */
  const [adminPayroll, setAdminPayroll] = useState<EmpPayroll[]>([]);
  const [adminLoading, setAdminLoading] = useState(true);

  /* Employee: own payslips from Firestore */
  const [myPayslips, setMyPayslips] = useState<Payslip[]>([]);
  const [empLoading, setEmpLoading] = useState(true);

  /* ── Admin: load payroll records ── */
  useEffect(() => {
    if (!isAdmin) return;
    const q = query(collection(db, "payroll"), orderBy("createdAt", "desc"));
    const unsub = onSnapshot(q, (snap) => {
      const rows: EmpPayroll[] = snap.docs.map((d) => {
        const data = d.data();
        return {
          id:          d.id,
          name:        data.employeeName  ?? "Unknown",
          dept:        data.department    ?? "—",
          salary:      data.basic         ?? 0,
          status:      data.status        ?? "Draft",
          month:       data.month         ?? "—",
          basic:       data.basic         ?? 0,
          allowances:  data.allowances    ?? 0,
          bonus:       data.bonus         ?? 0,
          pf:          data.pf            ?? 0,
          tax:         data.tax           ?? 0,
          deductions:  data.deductions    ?? 0,
          net:         data.net           ?? 0,
          employeeId:  data.employeeId    ?? "",
        };
      });
      setAdminPayroll(rows);
      setAdminLoading(false);
    }, () => setAdminLoading(false));
    return () => unsub();
  }, [isAdmin]);

  /* ── Employee: load own payslips from payroll collection ── */
  useEffect(() => {
    if (isAdmin || !profile?.employeeId) return;
    const q = query(
      collection(db, "payroll"),
      where("employeeId", "==", profile.employeeId),
      orderBy("createdAt", "desc")
    );
    const unsub = onSnapshot(q, (snap) => {
      const rows: Payslip[] = snap.docs.map((d) => {
        const data = d.data();
        return {
          id:         d.id,
          month:      data.month       ?? "—",
          basic:      data.basic       ?? 0,
          allowances: data.allowances  ?? 0,
          bonus:      data.bonus       ?? 0,
          pf:         data.pf          ?? 0,
          tax:        data.tax         ?? 0,
          deductions: data.deductions  ?? 0,
          net:        data.net         ?? 0,
          status:     data.status      ?? "Generated",
          employeeId: data.employeeId  ?? "",
        };
      });
      setMyPayslips(rows);
      setEmpLoading(false);
    }, () => setEmpLoading(false));
    return () => unsub();
  }, [isAdmin, profile?.employeeId]);

  /* ── Generate payroll for ALL active employees (admin) ── */
  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const now = new Date();
      const monthLabel = now.toLocaleString("default", { month: "long", year: "numeric" });

      // Fetch all active employees
      const empSnap = await getDocs(query(collection(db, "employees"), where("status", "==", "Active")));
      if (empSnap.empty) {
        toast.error("No active employees found. Add employees first.");
        setGenerating(false);
        return;
      }

      // Check if payroll already generated for this month
      const existingSnap = await getDocs(query(
        collection(db, "payroll"),
        where("month", "==", monthLabel)
      ));
      const existingMap: Record<string, string> = {};
      existingSnap.docs.forEach((d) => {
        existingMap[d.data().employeeId] = d.id;
      });

      let generated = 0;
      for (const empDoc of empSnap.docs) {
        const emp = empDoc.data();
        const empId = emp.employeeId ?? empDoc.id;
        const existingDocId = existingMap[empId];

        const basic       = Number(emp.salary ?? 0);
        const allowances  = 0;
        const bonus       = 0;
        const pf          = 0;
        const tax         = 0;
        const deductions  = 0;
        const net         = basic;

        const payload = {
          employeeId:   empId,
          employeeName: `${emp.firstName ?? ""} ${emp.lastName ?? ""}`.trim(),
          department:   emp.department    ?? "",
          month:        monthLabel,
          basic, allowances, bonus, pf, tax, deductions, net,
          status:       "Generated",
          companyId:    profile?.companyId ?? "default",
          createdBy:    profile?.displayName ?? "Admin",
          createdAt:    serverTimestamp(),
        };

        if (existingDocId) {
          await setDoc(doc(db, "payroll", existingDocId), payload);
        } else {
          await addDoc(collection(db, "payroll"), payload);
        }
        generated++;
      }

      if (generated === 0) {
        toast.info(`Payroll for ${monthLabel} already generated for all employees.`);
      } else {
        toast.success(`Payroll generated/updated for ${generated} employee${generated > 1 ? "s" : ""} — ${monthLabel}`);
      }
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate payroll. Please try again.");
    } finally {
      setGenerating(false);
    }
  };

  /* ── Stats ── */
  const totalPayroll   = adminPayroll.reduce((s, e) => s + e.net, 0);
  const generatedCount = adminPayroll.filter((e) => e.status === "Generated").length;
  const paidCount      = adminPayroll.filter((e) => e.status === "Paid").length;
  const pendingCount   = adminPayroll.filter((e) => e.status === "Draft" || e.status === "Generated").length;

  const selectedSlip = myPayslips.find((p) => p.id === selectedId) ?? myPayslips[0];

  return (
    <div className="page-container">
      {viewEntry && <PayslipModal entry={viewEntry} onClose={() => setViewEntry(null)} />}

      <div className="page-header">
        <div>
          <h1 className="page-title">Payroll</h1>
          <p className="page-subtitle">{isAdmin ? "Generate and manage employee payslips" : "View your salary details and payslip history"}</p>
        </div>
        {isAdmin && (
          <button id="payroll-generate" className="btn btn-primary" style={{ gap: 6 }} onClick={handleGenerate} disabled={generating}>
            {generating ? <Loader2 size={14} className="animate-spin" /> : <Plus size={14} />}
            {generating ? "Generating…" : "Generate Payroll"}
          </button>
        )}
      </div>

      {/* ── Admin View ── */}
      {isAdmin && (
        <>
          {/* Stats */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 14, marginBottom: 24 }}>
            {[
              { label: "Total Payroll", value: formatCurrency(totalPayroll), sub: "this cycle",      color: "var(--accent-purple)" },
              { label: "Generated",     value: String(generatedCount),       sub: "payslips",        color: "var(--accent-blue)"   },
              { label: "Paid",          value: String(paidCount),            sub: "employees",       color: "var(--accent-green)"  },
              { label: "Pending",       value: String(pendingCount),         sub: "to disburse",     color: "var(--accent-amber)"  },
            ].map((s) => (
              <div key={s.label} className="card" style={{ padding: "14px 18px" }}>
                <div style={{ fontSize: 22, fontWeight: 700, color: s.color, marginBottom: 4 }}>{s.value}</div>
                <div style={{ fontSize: 12, fontWeight: 500, color: "var(--text-secondary)", marginBottom: 2 }}>{s.label}</div>
                <div style={{ fontSize: 11, color: "var(--text-muted)" }}>{s.sub}</div>
              </div>
            ))}
          </div>

          {adminLoading ? (
            <div style={{ display: "flex", alignItems: "center", justifyContent: "center", padding: "48px 0", gap: 10, color: "var(--text-muted)" }}>
              <Loader2 size={18} className="animate-spin" />
              <span style={{ fontSize: 13 }}>Loading payroll…</span>
            </div>
          ) : adminPayroll.length === 0 ? (
            <div style={{ textAlign: "center", padding: "64px 0", color: "var(--text-muted)" }}>
              <DollarSign size={40} style={{ margin: "0 auto 12px", opacity: 0.3 }} />
              <p style={{ fontSize: 14 }}>No payroll records yet. Click &quot;Generate Payroll&quot; to create one.</p>
            </div>
          ) : (
            <div className="table-container">
              <table>
                <thead>
                  <tr>
                    <th>Employee</th><th>Department</th><th>Month</th><th>Net Salary</th><th>Status</th><th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {adminPayroll.map((e) => (
                    <tr key={e.id}>
                      <td>
                        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                          <div style={{ width: 30, height: 30, borderRadius: "50%", background: "var(--accent-blue-dim)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 600, color: "var(--accent-blue)" }}>
                            {e.name.split(" ").map((n) => n[0]).join("").slice(0, 2).toUpperCase()}
                          </div>
                          <span style={{ fontWeight: 500, fontSize: 13 }}>{e.name}</span>
                        </div>
                      </td>
                      <td style={{ fontSize: 13, color: "var(--text-secondary)" }}>{e.dept}</td>
                      <td style={{ fontSize: 13, color: "var(--text-secondary)" }}>{e.month}</td>
                      <td style={{ fontWeight: 600 }}>{formatCurrency(e.net)}</td>
                      <td>
                        <span className="badge" style={{
                          background: e.status === "Paid" ? "var(--accent-green-dim)" : e.status === "Generated" ? "var(--accent-blue-dim)" : "rgba(255,255,255,0.06)",
                          color: e.status === "Paid" ? "var(--accent-green)" : e.status === "Generated" ? "var(--accent-blue)" : "var(--text-muted)",
                        }}>{e.status}</span>
                      </td>
                      <td>
                        <div style={{ display: "flex", gap: 6 }}>
                          <button className="btn btn-ghost" style={{ padding: "4px 8px", fontSize: 12, gap: 4 }} onClick={() => setViewEntry(e)}>
                            <FileText size={12} /> View
                          </button>
                          <button className="btn btn-ghost" style={{ padding: "4px 8px", fontSize: 12, gap: 4 }} onClick={() => {
                            openPrintWindow(buildPayslipHtml(e));
                            toast.success(`Payslip PDF for ${e.name} opened!`);
                          }}>
                            <Download size={12} /> PDF
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}

      {/* ── Employee View ── */}
      {!isAdmin && (
        <>
          {empLoading ? (
            <div style={{ display: "flex", alignItems: "center", justifyContent: "center", padding: "48px 0", gap: 10, color: "var(--text-muted)" }}>
              <Loader2 size={18} className="animate-spin" />
              <span style={{ fontSize: 13 }}>Loading payslips…</span>
            </div>
          ) : myPayslips.length === 0 ? (
            <div style={{ textAlign: "center", padding: "64px 0", color: "var(--text-muted)" }}>
              <DollarSign size={40} style={{ margin: "0 auto 12px", opacity: 0.3 }} />
              <p style={{ fontSize: 14 }}>No payslips available yet. Your HR will generate them each month.</p>
            </div>
          ) : (
            <div style={{ display: "grid", gridTemplateColumns: "260px 1fr", gap: 20 }}>
              {/* History list */}
              <div>
                <div style={{ fontSize: 13, fontWeight: 600, color: "var(--text-secondary)", marginBottom: 10 }}>Payslip History</div>
                <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                  {myPayslips.map((p) => (
                    <button key={p.id} onClick={() => setSelectedId(p.id)} style={{
                      display: "flex", justifyContent: "space-between", alignItems: "center",
                      padding: "12px 14px", borderRadius: "var(--radius-sm)", cursor: "pointer",
                      background: (selectedId ?? myPayslips[0]?.id) === p.id ? "var(--accent-blue-dim)" : "var(--bg-secondary)",
                      border: `1px solid ${(selectedId ?? myPayslips[0]?.id) === p.id ? "rgba(59,130,246,0.3)" : "var(--border)"}`,
                      transition: "all 0.15s", textAlign: "left",
                    }}>
                      <div>
                        <div style={{ fontSize: 13, fontWeight: 500, color: "var(--text-primary)" }}>{p.month}</div>
                        <div style={{ fontSize: 12, color: "var(--text-muted)" }}>{formatCurrency(p.net)} net</div>
                      </div>
                      <span className="badge badge-green" style={{ fontSize: 10 }}>{p.status}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Payslip detail */}
              {selectedSlip && (
                <div className="card" style={{ padding: 28 }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}>
                    <div>
                      <div style={{ fontSize: 16, fontWeight: 700 }}>Payslip — {selectedSlip.month}</div>
                      <div style={{ fontSize: 12, color: "var(--text-muted)", marginTop: 2 }}>Generated by HR · Credited on 1st</div>
                    </div>
                    <button id="payslip-download" className="btn btn-secondary" style={{ gap: 6 }} onClick={() => {
                      openPrintWindow(buildPayslipHtml({
                        name: profile?.displayName ?? "Employee",
                        dept: "Your Department",
                        ...selectedSlip,
                      }));
                      toast.success("Payslip opened for download!");
                    }}>
                      <Download size={14} /> Download PDF
                    </button>
                  </div>

                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
                    <div>
                      <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-muted)", marginBottom: 12, letterSpacing: "0.05em", textTransform: "uppercase" }}>Earnings</div>
                      {[
                        { label: "Basic Salary",  value: formatCurrency(selectedSlip.basic) },
                        { label: "Allowances",    value: formatCurrency(selectedSlip.allowances) },
                        { label: "Bonus",         value: formatCurrency(selectedSlip.bonus) },
                      ].map((item) => (
                        <div key={item.label} style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid var(--border)" }}>
                          <span style={{ fontSize: 13, color: "var(--text-secondary)" }}>{item.label}</span>
                          <span style={{ fontSize: 13, fontWeight: 500 }}>{item.value}</span>
                        </div>
                      ))}
                      <div style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", marginTop: 4 }}>
                        <span style={{ fontSize: 13, fontWeight: 600 }}>Gross Salary</span>
                        <span style={{ fontSize: 13, fontWeight: 700, color: "var(--accent-green)" }}>{formatCurrency(selectedSlip.basic + selectedSlip.allowances + selectedSlip.bonus)}</span>
                      </div>
                    </div>
                    <div>
                      <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-muted)", marginBottom: 12, letterSpacing: "0.05em", textTransform: "uppercase" }}>Deductions</div>
                      {[
                        { label: "Provident Fund", value: formatCurrency(selectedSlip.pf) },
                        { label: "Income Tax",     value: formatCurrency(selectedSlip.tax) },
                      ].map((item) => (
                        <div key={item.label} style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid var(--border)" }}>
                          <span style={{ fontSize: 13, color: "var(--text-secondary)" }}>{item.label}</span>
                          <span style={{ fontSize: 13, fontWeight: 500, color: "var(--accent-red)" }}>- {item.value}</span>
                        </div>
                      ))}
                      <div style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", marginTop: 4 }}>
                        <span style={{ fontSize: 13, fontWeight: 600 }}>Total Deductions</span>
                        <span style={{ fontSize: 13, fontWeight: 700, color: "var(--accent-red)" }}>- {formatCurrency(selectedSlip.deductions)}</span>
                      </div>
                    </div>
                  </div>

                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 20, padding: "16px 20px", background: "var(--accent-green-dim)", borderRadius: "var(--radius-sm)", border: "1px solid rgba(34,197,94,0.2)" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                      <CheckCircle2 size={18} color="var(--accent-green)" />
                      <span style={{ fontSize: 15, fontWeight: 700 }}>Net Salary</span>
                    </div>
                    <span style={{ fontSize: 22, fontWeight: 800, color: "var(--accent-green)" }}>{formatCurrency(selectedSlip.net)}</span>
                  </div>
                </div>
              )}
            </div>
          )}
        </>
      )}
    </div>
  );
}
